version: "3"
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ${PWD}/prometheus:/prometheus-data
    command: --config.file=/prometheus-data/prometheus.yml
    ports:
      - 9090:9090
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - 80:80
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125/udp
      - 8126:8126
  grafana:
    image: grafana/grafana
    volumes:
      - ${PWD}/grafana/datasources:/etc/grafana/provisioning/datasources/
      - ${PWD}/grafana/dashboards:/etc/grafana/provisioning/dashboards/
    ports:
      - 3000:3000
  postgres-14:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: "prisma"
    ports:
      - "5434:5432"
  otel:
    image: jaegertracing/all-in-one:1.35
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
