{
 "title": "Prisma StatsD",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Operations vs Queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "perSecond(stats.gauges.prisma.query_total_operations)"
    },
    {
     "target": "perSecond(stats.gauges.prisma.query_total_queries)"
    }
   ]
  },
  {
   "title": "Transactions vs Active and Idle Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "stats.gauges.prisma.query_active_transactions"
    },
    {
     "target": "stats.gauges.prisma.pool_active_connections"
    },
    {
     "target": "stats.gauges.prisma.pool_idle_connections"
    }
   ]
  },
  {
   "title": "Operation vs Query Mean 90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "stats.timers.prisma.query_total_elapsed_time_ms.mean_90"
    },
    {
     "target": "stats.timers.prisma.query_operation_total_elapsed_time_ms.mean_90"
    }
   ]
  }
 ]
}