{
 "title": "Prisma Prometheus",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "95% Total Operation Elapsed Time vs Query Elapsed Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(query_operation_total_elapsed_time_ms_bucket[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(query_total_elapsed_time_ms_bucket[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Active vs Idle connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "pool_active_connections" },
    { "expr": "pool_idle_connections" },
    { "expr": "pool_wait_count" }
   ]
  },
  {
   "title": "Operations vs Queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(query_total_operations[$__rate_interval])"
    },
    {
     "expr": "rate(query_total_queries[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Active Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "query_active_transactions" },
    {}
   ]
  }
 ]
}