datasources:
-  access: 'proxy'                       # make grafana perform the requests
   editable: true                        # whether it should be editable
   is_default: true                      # whether this should be the default DS
   name: 'prom1'                         # name of the datasource
   org_id: 1                             # id of the organization to tie this datasource to
   type: 'prometheus'                    # type of the data source
   url: 'http://prometheus:9090'         # url of the prom instance
   version: 1   
-  access: 'proxy'                       # make grafana perform the requests
   editable: true                        # whether it should be editable
   is_default: false                      # whether this should be the default DS
   name: 'statsd'                         # name of the datasource
   org_id: 1                             # id of the organization to tie this datasource to
   type: 'graphite'                    # type of the data source
   url: 'http://graphite:80'         # url of the prom instance
   version: 1   
-  access: 'proxy'
   editable: true
   is_default: false                      # whether this should be the default DS
   name: 'Jaeger'                         # name of the datasource
   org_id: 1                             # id of the organization to tie this datasource to
   type: 'jaeger'                    # type of the data source
   url: 'http://otel:16686'         # url of the prom instance

